data:
  root: "./data/LOLdataset"
  train_dir: "train"
  test_dir: "test"
  input_dir: "low"
  target_dir: "light"
  image_size: 256

model:
  num_stages: 8
  proxnet_hidden: 16
  proxnet_blocks: 2
  gamma: 2.2
  share_channel_weights: false

loss:
  charbonnier: 1.0
  charbonnier_reduction: "mean"
  perceptual: 0.12
  perceptual_criterion: "l2"
  perceptual_reduction: "mean"
  ssim: 0.2
  ssim_range: 1.0
  grad: 0.05
  fourier_real: 0.5
  fourier_imag: 0.5  
  intermediate: 0.1
  intermediate_increasing_weight: false

training:
  model_dir: "outputs/fdunet_lol"
  optimization:
    optimizer:
      name: "adamw"
      lr: 0.0002
      weight_decay: 0.001
      betas: [0.9, 0.999]
    scheduler:
      name: "cosineannealinglr"
      T_max: 200      
      eta_min: 0.000001 

evaluation:
  save_images: false